sudo: required

language: node_js
node_js:
  - "5"

services:
  - docker

install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t pacesys/openstack4j.com .
  - docker run -d -p 127.0.0.1:80:80 --name os4j pacesys/openstack4j.com

script:
  - docker ps | grep -q os4j

after_success:
  - docker push pacesys/openstack4j.com

# whitelist
branches:
  only:
    - master

