# Jekyll
permalink: pretty
paginate: 10 
name: OpenStack4j
baseurl: 
markdown: kramdown
version: 2.0.3
snapshot-version: 2.0.4-SNAPSHOT
withdeps-version: 2.0.4-withdeps
url: http://www.openstack4j.com
