# Jekyll
permalink: pretty
paginate: 10 
name: OpenStack4j
baseurl: 
markdown: kramdown
version: 2.0.7
snapshot-version: 2.0.8-SNAPSHOT
withdeps-version: 2.0.8-withdeps
url: http://www.openstack4j.com
